export default {
    useGitignore: true,
    cache: {
        useCache: true,
        cacheLocation: 'node_modules/.cache/cspell/.cspellcache',
        cacheStrategy: 'content',
    },
    ignoreWords: [
        'biomejs',
        'filenaming',
        'rimac',
        'tsup',
        'pinst',
        'postpack',
        'conventionalcommits',
        'ENOAUTHORIZATION',
        'ENOIMAGE',
        'EDEPLOY',
        'ENOACCESSKEYID',
        'ENOAUTHENTICATION',
        'ENOIMAGENAME',
        'ENOREGION',
        'ENOSECRETACCESSKEY',
        'ECOMMAND',
    ],
}
